version: "3"

services:
  postgres:
    container_name: "sentinet-postgres"
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data/"
  redis:
    container_name: "sentinet-redis"
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - "redisdata:/data"

volumes:
  pgdata:
  redisdata:
