CREATE TYPE PROTOCOL AS ENUM ('TCP', 'UDP');

CREATE TABLE "packets" (
  capture_datetime TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  src VARCHAR(15) NOT NULL,
  sport INTEGER NOT NULL,
  dst VARCHAR(15) NOT NULL,
  dport INTEGER NOT NULL,
  proto PROTOCOL NOT NULL
);